#!/usr/bin/env python3
"""Generate src/generated/embedded_assets.h by bundling every PNG/SVG under
assets/figma/images/ and assets/icons/ into a C++ header.

The bundled binary then has no filesystem dependency: ui::asset_path("X")
(see ui/components.cpp) writes the matching bytes to /tmp/egt-asset-X on
first use and returns the path. This avoids the target-vs-simulator path
divergence — both work without an external assets/ directory.

Run after adding/changing any asset:
    scripts/gen-embedded-assets.py
"""

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SRC_DIRS = [ROOT / "assets" / "figma" / "images",
            ROOT / "assets" / "icons"]
OUT = ROOT / "src" / "generated" / "embedded_assets.h"

# Identifiers must be valid C: assets_figma_images_Lice_logo_png etc.
def ident(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    s = re.sub(r"[^A-Za-z0-9]", "_", rel)
    return s


def short_name(path: Path) -> str:
    """Short lookup key used by ui::asset_path() — file basename without ext."""
    return path.stem


def emit_blob(out, ident_name: str, data: bytes) -> None:
    out.write(f"static const unsigned char {ident_name}[] = {{\n  ")
    cols = 12
    for i, b in enumerate(data):
        out.write(f"0x{b:02x},")
        if (i + 1) % cols == 0:
            out.write("\n  ")
        else:
            out.write(" ")
    out.write(f"\n}};\nstatic const unsigned int {ident_name}_len = {len(data)};\n\n")


def main() -> int:
    assets = []
    for d in SRC_DIRS:
        if not d.exists():
            continue
        for p in sorted(d.iterdir()):
            if p.suffix.lower() in (".png", ".svg") and p.is_file():
                assets.append(p)

    if not assets:
        print(f"no assets found under {SRC_DIRS}", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as out:
        out.write("// AUTO-GENERATED by scripts/gen-embedded-assets.py — DO NOT EDIT.\n")
        out.write("// Bundles every asset under assets/figma/images/ + assets/icons/\n")
        out.write("// so the target binary has no filesystem dependency on the assets.\n")
        out.write("// Use ui::asset_path(<basename-without-ext>) to materialise an asset\n")
        out.write("// into /tmp at first use and get the path string back.\n\n")
        out.write("#pragma once\n#include <cstddef>\n#include <utility>\n\n")
        for p in assets:
            data = p.read_bytes()
            emit_blob(out, ident(p), data)

        # Lookup table: { "short-name" -> (bytes_ptr, len) }
        out.write("// ── Lookup table indexed by basename (without extension) ───────────\n")
        out.write("namespace embedded_assets {\n")
        out.write("struct Asset { const char* name; const unsigned char* data; unsigned int len; const char* ext; };\n")
        out.write("inline const Asset kAll[] = {\n")
        for p in assets:
            out.write(
                f'    {{ "{short_name(p)}", '
                f'{ident(p)}, {ident(p)}_len, "{p.suffix.lstrip(".")}" }},\n'
            )
        out.write("};\n")
        out.write(f"inline constexpr std::size_t kCount = {len(assets)};\n")
        out.write("}  // namespace embedded_assets\n")

    print(f"[gen-embedded-assets] wrote {OUT} with {len(assets)} assets "
          f"({sum(p.stat().st_size for p in assets)} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
